name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ResearchSoftwareActions/CleanNotebookAction@1.0
      with:
        disable-checks: outputs,execution_count
